### ISSUE TITLE
Create stat calculator

### ISSUE THREAD

**Issue by Xillians** [Xillians/circus-acts#9]
We need to ensure the controller has tracks of all relevant bonuses and start stats. 

## Tasks
- [ ] #8 
- [ ] Create logic for temporary upgrade bonuses
- [ ] Create logic for advertisement bonuses
- [ ] Create logic for event bonuses
- [ ] Create logic for custom bonuses
- [ ] Make controller use logic to calculate total
- [ ] Present total on web app as non-editable value
